### ISSUE TITLE
Bulk adding pitch accent to more than one field in one card

### ISSUE THREAD

**Issue by irtykev** [IllDepence/anki_add_pitch_plugin#10]
Hi,
First, let me thank you very much for your work. This add-on gives me a lot of help when I'm trying to learn Japanese vocabulary. I'm really thankful for your time and resource you put in to this.
Lately I'm trying to study a Kanji deck. The field of cards in this deck are Kanji, Kanji reading, Kanji meaning, example word 1 (that using this Kanji), example word 1 reading, example 1 meaning, example word 2, example word 2 reading, example 2 meaning etc. As I thought it would be great if I could bulk add the pitch accent to all the example words from one Kanji card, the add-on would not do it. It skipped the card if there are already one accent information, so I only got only one example word with pitch accent svg.
I tested with the word 木曜日 (もくようび). If I bulk add the pitch accent when there isn't any accent information on the card, the accent for this word will show up. If I bulk add the accent information for other example words in the same card before bulk add accent for this word, it won't show up.
I know I could find the accent information and add the accent manually. But there are thousands of cards with more than one example word, so I want to ask first if I missed some steps or instructions? Or would it be possible if this add-on could check if there is already accent information in the field, instead of the card, before it decides to skip?
Thanks!

**Comment by IllDepence** [comment]
Hi,
glad you find the add-on useful.


Interesting use case. If I understand you correctly the example words are in separate fields, correct? I've modified the plugin such that it should allow you to bulk add pitch annotations to multiple fields. You can **[download it here](http://moc.sirtetris.com/japanese_pitch_accent.ankiaddon)**.

Could you see if that does the deal on your end?
If so I'd also update the version on ankiweb accordingly.

**Comment by irtykev** [comment]
Thanks for your kind response.
I tried to install the plugin, but Anki said "Error installing japanese_pitch_accent.ankiaddon: Invalid add-on manifest. Please report this to the respective add-on author(s)."
So I uninstalled the original add-on and reinstall this plugin. Still got an error. Then I reinstalled Anki and installed the plugin again. The error still popped up.
I'm using Anki version ⁨2.1.38.

**Comment by IllDepence** [comment]
I wasn't aware ankiweb automatically adds metadata to the add-on. Should be fixed now. Could you try again?

**Comment by irtykev** [comment]
Done. There is no error. The plugin works like a charm. I can bulk add pitch annotations to multiple fields now. Thank you very, very much. ^^

**Comment by IllDepence** [comment]
Great! :)
I've updated the version on ankiweb now too.
