### ISSUE TITLE
Support for only pitch numbers

### ISSUE THREAD

**Issue by eshrh** [IllDepence/anki_add_pitch_plugin#15]
I would like to add pitch information to many thousands of cards at once, but I don't need the pitch graphs. All i need is the number that indicates where the pitch falls. This information is already included in the wadoku_pitchdb that comes with this addon.

Would this be possible to implement?

Thanks, I appreciate the addon a lot!

**Comment by eshrh** [comment]
I needed this to retroactively add pitch numbers to yomichan cards, i was able to do this using ankipandas with this: https://gist.github.com/eshrh/715482a3ff02723a9225e8f040069059

**Comment by IllDepence** [comment]
Hi,

glad to hear you were able to make good use of the pitchdb. Side note: it's based on a Wadoku XML dump ([donwload page in German](https://www.wadoku.de/wiki/display/WAD/Downloads+und+Links)) which appears to get updated regularly.

Also, thanks for mentioning ankipandas! I was not aware that exists. (‌‌:

(I presume you were able to achieve what you wanted to do using the Jupyter notebook you linked to, therefore I'll close the issue.)
