### ISSUE TITLE
Incorrect readings 

### ISSUE THREAD

**Issue by sanjiro-san** [IllDepence/anki_add_pitch_plugin#2]
I have some incorrect readings, for example for 生　(せい)　I got いき. As a Reading field I am using field with Japanese Support add-on furigana, so I don't have just kana there, I have kanji + hiragana (I don't know if that could be a problem). Can I somehow correct them manually? It seems I cannot edit the field (or manually remove it at all).

**Comment by IllDepence** [comment]
If you want to manually edit or remove the accent into from a card, use the Edit HTML option ([screenshot](https://i.imgur.com/gtr6FRx.jpg)). The accent info is everything between the markers `<!-- accent_start -->` and  `<!-- accent_end -->`.

As for manual changes, you could use [this simple web interface](https://illdepence.github.io/SVG_pitch/) I created. Either use the automatic version, type in 生 and go through the readings until it displays the one you want on your card, or use the manual version and enter せい into the text field and hll into the pitch field. In either way you should then be able to copy the contents of the SVG field and replace the reading on your card while editing it in HTML mode.

**Comment by sanjiro-san** [comment]
Thanks a lot!

**Comment by IllDepence** [comment]
Hey @sanjiro-san 

I just [updated the plugin](https://github.com/IllDepence/anki_add_pitch_plugin) and it now lets you individually add/edit/remove pitch accent annotations from the card editor. :)
