### ISSUE TITLE
Unable to add pitch accent to sentences within 2k/6k deck

### ISSUE THREAD

**Issue by Sierra004** [IllDepence/anki_add_pitch_plugin#21]
When looking in the fields for Expression and reading. The target vocabulary within the example sentence is bolded and displays like this within the card editor: < b> その < /b> 人がいいです　And the Katakana version is also in bold for the target word. I think this is causing the insertion of pitch accent to fail.

Is there a way to fix this issue? Thanks for the great Add on

**Comment by IllDepence** [comment]
Hi Sierra004,
thank you for your feedback. Unfortunately the add-on just works for single words or set phrases that you would find in the dictionary (it takes the whole contents of the expression field to look up the pitch accent).

To support a case like you describe, a special function for selecting the bolded part would need to be written just for the 2k/6k deck. For your own use, you could, for example, adjust the `clean()` function in the add-on’s `util.py` to achieve this.
