### ISSUE TITLE
Outdated database

### ISSUE THREAD

**Issue by kclisp** [IllDepence/anki_add_pitch_plugin#22]
Thanks for your great add-on.

It seems that it's unable to find common words such as 突然, 試す, 覚める, 味方, 親切, 触る, etc., even though they are on the wadoku site. This might be because your copy of the database is outdated.

**Comment by kclisp** [comment]
Hi again, I ran your wadoku_parse.py on the newest Wadoku XML dump, and it seems to work nicely. I was wondering what your thoughts are on shipping the plugin with the newest csv file created from the dump?

**Comment by IllDepence** [comment]
Hi kclisp,

thanks for bringing this up. I was not aware that the Wadoku XML dump had grown this much. On my end the parsing and integration into the plugin also worked without any problems. I’ll go ahead package the updated `wadoku_pitchdb.csv` into an update on ankiweb. 👍
