### ISSUE TITLE
HTML source view introduced in Anki 2.1.45 removes HTML comments from beginning of fields

### ISSUE THREAD

**Issue by IllDepence** [IllDepence/anki_add_pitch_plugin#25]
See detailed description here: https://github.com/IllDepence/anki_add_pitch_plugin/issues/24#issuecomment-1024982096

~~TODO:~~
* ~~Test possible wordarounds (e.g. adding a zero width non-joiner or similar in front of the pitch accent start marker)~~
* ~~Consider implementing a function that detects if a field *only* contains a pitch accent pattern SVG with missing start marker~~
* ~~Consider implementing a function to remove *all* contents from a certain field of *all* cards of a deck to fix large amounts of cards with double pitch accent pattern~~

/edit:

reported as an Anki bug: https://github.com/ankitects/anki/issues/1644
fixed: https://github.com/ankitects/anki/pull/1647

**Comment by billzt** [comment]
Thanks. this bug has been fixed in anki 2.1.50beta3

**Comment by IllDepence** [comment]
Jup, the Anki developers were super quick to act on that one. :)

**Comment by IllDepence** [comment]
reported as an Anki bug: https://github.com/ankitects/anki/issues/1644
fixed: https://github.com/ankitects/anki/pull/1647
