### ISSUE TITLE
Night mode visibility

### ISSUE THREAD

**Issue by wol-kylus** [IllDepence/anki_add_pitch_plugin#32]
Hi there,
I'm having trouble trying to make the pitch accent graph visible in night mode. I'd appreciate some help in this regard.
Thanks.

**Comment by IllDepence** [comment]
Hi,

the [plugin page](https://ankiweb.net/shared/info/148002038) has a section “Annotations are customizable via CSS” with the following examples:

```
svg.pitch { height: 150px; width: auto; }
svg.pitch text { font-weight: bold !important; }
svg.pitch > path { stroke: #fa7 !important; }
svg.pitch > circle[r="5"] { fill: #fa7 !important; }
svg.pitch > circle[r="3.25"] { fill: #cf9 !important; 
```

By adjusting the stiling of the notes your deck uses you should be able to change the color of the text, circles and lines in this way. If you try this and any particular problems or questions come up, let me know. :)

**Comment by wol-kylus** [comment]
Hi, thanks for replying.
I'm not well-versed in CSS, I'd appreciate it if you could show me how to change the color of the hiragana readings below the pitch accent graph. Thanks.

**Comment by IllDepence** [comment]
Hi, 

something like this should change the hiragana color: `svg.pitch text { fill: #eaeaea !important; }`.
Replace the `eaeaea` with the color you want ([here’s a color picker](https://www.w3schools.com/colors/colors_picker.asp)).

**Comment by wol-kylus** [comment]
Hi,
it worked, thanks a lot for helping me.
