### ISSUE TITLE
"No cards found" when bulk adding to a deck with subdecks

### ISSUE THREAD

**Issue by kevinwjin** [IllDepence/anki_add_pitch_plugin#34]
When bulk adding pitch accent to decks that have subdecks, the error "no cards found" is returned. It is currently necessary to bulk add to each subdeck within the larger deck. This is very cumbersome and unrealistic for decks with a large number of subdecks, which describes a lot of community-contributed Japanese vocabulary decks that are available.

Here, I have clicked "bulk add" and attempt to select a deck with many subdecks...

![image](https://user-images.githubusercontent.com/98922764/185718548-62fa72a1-a019-47fa-b7d8-47d73b756a51.png)

...only to be met with this error.

![image](https://user-images.githubusercontent.com/98922764/185718344-f930b5f8-8527-46da-be11-587e603ee247.png)

For comparison, I bulk add to a deck with no subdecks...

![image](https://user-images.githubusercontent.com/98922764/185718455-26dc0caf-b4ce-4f9e-817e-7b49e5cec457.png)

...and it works.

![image](https://user-images.githubusercontent.com/98922764/185718469-32cd69f3-bc73-41a5-ba0f-64cb3e2ccd94.png)

Anki version: 2.1.54
Operating system: macOS Monterey 12.5.1

**Comment by IllDepence** [comment]
Apologies for never reacting to your issue.
The feature request for handling sub-decks is now tracked in #45.
