### ISSUE TITLE
No pitch data issue

### ISSUE THREAD

**Issue by c0c0loco** [IllDepence/anki_add_pitch_plugin#41]
It's driving me crazy. I used this addon last year and I had no issues installing it. Did every single step, followed this and this tutorial. The addon works if I say to add the pitch accent in bulk but it does not work if I try to mine new flashcards. I don't know what's going on but I give up. I tried installing different pitch accent dictionaries, switching the pitch accent field, etc. I can add the pitch accent manually but it I click on the flashcard to do it manually it can't, it says this: _Anki encountered a problem. Please follow the troubleshooting steps. Complementos posiblemente implicados: ⁨Japanese Pitch Accent_
Sharing screenshots of my settings, please help me! Also, it's on the right deck and model...
![image](https://github.com/IllDepence/anki_add_pitch_plugin/assets/149329867/5201b741-4790-4cec-955c-db7039b09a5d)
![image](https://github.com/IllDepence/anki_add_pitch_plugin/assets/149329867/74a1dd03-55a0-42bb-be3c-7f306ec281dd)
![image](https://github.com/IllDepence/anki_add_pitch_plugin/assets/149329867/24279033-3613-427f-b776-8ddbec863988)

**Comment by IllDepence** [comment]
Hi

sure, I will try my best to help you. Let’s first make sure I understand your situation correctly.

You write:

> The addon works if I say to add the pitch accent in bulk but it does not work if I try to mine new flashcards.

1. So bulk adding works as expected, correct?
2. But adding on single cards using either of the two buttons shown below does not work. correct?

![](https://raw.githubusercontent.com/IllDepence/anki_add_pitch_plugin/master/doc/ankiweb_img/editor_1.jpg)
![](https://raw.githubusercontent.com/IllDepence/anki_add_pitch_plugin/master/doc/ankiweb_img/editor_2.jpg)

If this is the case, as a temporary solution you can simply use the bulk add function whenever you added some cards. It will only add a pitch accent to the new cards.

Aside from that, it would be interesting to find the problem behind the error when adding to a single card. Does it also happen when you run Anki with *only* the pitch accent addon active and no other addons?

**Comment by IllDepence** [comment]
Closing this for the moment as there is no further input. Please feel free to get back at any time to resume.
